<a href="https://colab.research.google.com/github/Shavindri/Final-Year-Project/blob/main/Final_Year_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Evaluating the Effectiveness of User Awareness and Front-End Security Measures in Online Banking**

The data analysis for this study was implemented using Python within the Google Colab environment to ensure a structured, reproducible, and efficient analytical process. Following the collection of questionnaire responses through Google Forms, the dataset was imported into Python for preprocessing and statistical analysis. The implementation incorporates a range of Python libraries, including Pandas and NumPy for data manipulation, Matplotlib and Seaborn for data visualisation, SciPy and Pingouin for statistical and reliability analyses, and Scikit-learn for machine learning model development. The code performs data cleaning, preprocessing, descriptive statistical analysis, reliability testing using Cronbach's Alpha, correlation analysis, hypothesis testing, and predictive modelling. In addition, the processed dataset and trained machine learning model are exported for integration into the Online Banking Cybersecurity Awareness Toolkit, ensuring that the analytical findings are translated into a practical educational application.

Student : Shavindri Kuweju

Student number : 20336291

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display

# Configure visual style
sns.set(style='whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12

# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
%cd "/content/drive/MyDrive/FYP"

/content/drive/MyDrive/FYP

In [5]:
#imported from a CSV file into a Pandas DataFrame

path = "Evaluating the Effectiveness of User Awareness and Front-End Security Measures in Online Banking (Responses).csv"

all_data = pd.read_csv(path)

all_data.head()

,Timestamp,Please confirm the following before proceeding with the survey:\nPlease tick all of the above boxes to continue to the questionnaire.,What is your age?,Gender,Highest Level of Education,How often do you use online banking?,Which online banking platform do you use most frequently?,I can recognise phishing emails pretending to be from a bank,I know that legitimate banks never ask customers to share OTPs or passwords.,I understand how Multi-Factor Authentication (MFA) protects online banking accounts,...,I regularly update my banking application.,I verify website authenticity before entering my banking credentials.,"I understand how biometric authentication (e.g., Face ID or fingerprint recognition) works when I log in to my online banking account.","I understand how my biometric data (e.g., Face ID or fingerprint) is stored and protected when I use biometric authentication for online banking.",I am concerned about the privacy risks associated with using biometric authentication for online banking.,I trust that my biometric data is securely protected when I use biometric authentication for online banking.,Banks should provide clearer information about how biometric data is used and protected when customers use biometric authentication for online banking.,Concerns about biometric privacy would affect my willingness to use biometric authentication for online banking.,Which biometric authentication method do you currently use for online banking?,"In your opinion, what is the biggest concern when using biometric authentication for online banking?"
0,7/3/2026 22:45:15,I have read and understood the information pro...,25–34,Female,Master's Degree,Weekly,Both equally,2,1,2,...,Sometimes,Sometimes,3,2,2,2,2,2,"Face ID / Facial Recognition, Fingerprint Reco...",Risk of biometric data being stolen
1,7/4/2026 9:47:05,I have read and understood the information pro...,25–34,Male,Secondary School,Daily,Internet Banking Website,1,1,1,...,Always,Always,1,3,3,3,1,1,Fingerprint Recognition,"Privacy of biometric data, Risk of biometric d..."
2,7/4/2026 10:18:23,I have read and understood the information pro...,25–34,Female,Diploma,Daily,Mobile Banking App,1,1,1,...,Always,Sometimes,1,2,1,2,1,1,Face ID / Facial Recognition,Accuracy of biometric authentication
3,7/4/2026 10:34:06,I have read and understood the information pro...,18-24,Male,Bachelor's Degree,Weekly,Mobile Banking App,3,1,1,...,Rarely,Rarely,2,3,4,3,3,1,Face ID / Facial Recognition,I have no concerns
4,7/4/2026 10:43:17,I have read and understood the information pro...,18-24,Female,Master's Degree,Daily,Mobile Banking App,1,1,1,...,Always,Always,1,1,2,1,2,2,Face ID / Facial Recognition,Accuracy of biometric authentication

In [6]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 41 columns):
 #   Column                                                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                                                   --------------  -----
 0   Timestamp                                                                                                                                                59 non-null     object
 1   Please confirm the following before proceeding with the survey:
Please tick all of the above boxes to continue to the questionnaire.                     59 non-null     object
 2   What is your age?                                                                                                                                        59 non-null     object
 3   Gender                                                                                                                                                   59 non-null     object
 4   Highest Level of Education                                                                                                                               59 non-null     object
 5   How often do you use online banking?                                                                                                                     59 non-null     object
 6   Which online banking platform do you use most frequently?                                                                                                59 non-null     object
 7   I can recognise phishing emails pretending to be from a bank                                                                                             59 non-null     int64
 8   I know that legitimate banks never ask customers to share OTPs or passwords.                                                                             59 non-null     int64
 9   I understand how Multi-Factor Authentication (MFA) protects online banking accounts                                                                      59 non-null     int64
 10  I know how to verify that a banking website is genuine before entering my login credentials.                                                             59 non-null     int64
 11  I understand the risks of using public Wi-Fi for online banking.                                                                                         59 non-null     int64
 12  I am aware of AI-generated scams and deepfake fraud targeting banking customers.                                                                         59 non-null     int64
 13  I know what actions to take if I suspect my online banking account has been compromised.                                                                 59 non-null     int64
 14  Have you ever received a phishing email pretending to be from a bank?                                                                                    59 non-null     object
 15  Have you ever received a suspicious SMS claiming to be from a bank?                                                                                      59 non-null     object
 16  Have you ever received a phone call claiming to be from your bank asking for personal information?                                                       59 non-null     object
 17  Have you ever clicked on a suspicious banking link?                                                                                                      59 non-null     object
 18  Have you ever experienced online banking fraud?                                                                                                          59 non-null     object
 19  If yes, how did you identify or respond to the phishing attempt?
(Select all that apply)                                                                 40 non-null     object
 20  You receive an email claiming your bank account will be suspended unless you click a link immediately.
What would you do?                                59 non-null     object
 21  Someone claiming to be from your bank asks for your OTP to verify your identity.
What would you do?                                                      59 non-null     object
 22  You receive a security alert saying someone logged into your account from another device.
What is your first action?                                     59 non-null     object
 23  You receive a voice call that sounds exactly like your bank manager asking you to urgently approve a transaction.
What would you do?                     59 non-null     object
 24  Multi-Factor Authentication (MFA) improves online banking security.                                                                                      59 non-null     int64
 25  Biometric authentication (Face ID/Fingerprint) provides better protection than passwords alone.                                                          59 non-null     int64
 26  Bank security alerts help prevent cyberattacks.                                                                                                          59 non-null     int64
 27  Current front-end security measures provide adequate protection against emerging cyber threats.                                                          59 non-null     int64
 28  AI-based fraud detection systems improve online banking security.                                                                                        59 non-null     int64
 29  I use a unique password for my online banking account.                                                                                                   59 non-null     object
 30  I enable Multi-Factor Authentication whenever it is available.                                                                                           59 non-null     object
 31  I regularly update my banking application.                                                                                                               59 non-null     object
 32  I verify website authenticity before entering my banking credentials.                                                                                    59 non-null     object
 33  I understand how biometric authentication (e.g., Face ID or fingerprint recognition) works when I log in to my online banking account.                   59 non-null     int64
 34  I understand how my biometric data (e.g., Face ID or fingerprint) is stored and protected when I use biometric authentication for online banking.        59 non-null     int64
 35  I am concerned about the privacy risks associated with using biometric authentication for online banking.                                                59 non-null     int64
 36  I trust that my biometric data is securely protected when I use biometric authentication for online banking.                                             59 non-null     int64
 37  Banks should provide clearer information about how biometric data is used and protected when customers use biometric authentication for online banking.  59 non-null     int64
 38  Concerns about biometric privacy would affect my willingness to use biometric authentication for online banking.                                         59 non-null     int64
 39  Which biometric authentication method do you currently use for online banking?                                                                           59 non-null     object
 40  In your opinion, what is the biggest concern when using biometric authentication for online banking?                                                     59 non-null     object
dtypes: int64(18), object(23)
memory usage: 19.0+ KB

In [7]:
# Check exact column names
for i, col in enumerate(all_data.columns):
    print(i, col)

0 Timestamp
1 Please confirm the following before proceeding with the survey:
Please tick all of the above boxes to continue to the questionnaire.
2 What is your age?
3 Gender
4 Highest Level of Education
5 How often do you use online banking?
6 Which online banking platform do you use most frequently?
7 I can recognise phishing emails pretending to be from a bank
8 I know that legitimate banks never ask customers to share OTPs or passwords.
9 I understand how Multi-Factor Authentication (MFA) protects online banking accounts
10 I know how to verify that a banking website is genuine before entering my login credentials.
11 I understand the risks of using public Wi-Fi for online banking.
12 I am aware of AI-generated scams and deepfake fraud targeting banking customers.
13 I know what actions to take if I suspect my online banking account has been compromised.
14 Have you ever received a phishing email pretending to be from a bank?
15 Have you ever received a suspicious SMS claiming to be from a bank?
16 Have you ever received a phone call claiming to be from your bank asking for personal information?
17 Have you ever clicked on a suspicious banking link?
18 Have you ever experienced online banking fraud?
19 If yes, how did you identify or respond to the phishing attempt?
(Select all that apply)
20 You receive an email claiming your bank account will be suspended unless you click a link immediately.
What would you do?
21 Someone claiming to be from your bank asks for your OTP to verify your identity.
What would you do?
22 You receive a security alert saying someone logged into your account from another device.
What is your first action?
23 You receive a voice call that sounds exactly like your bank manager asking you to urgently approve a transaction.
What would you do?
24 Multi-Factor Authentication (MFA) improves online banking security.
25 Biometric authentication (Face ID/Fingerprint) provides better protection than passwords alone.
26 Bank security alerts help prevent cyberattacks.
27 Current front-end security measures provide adequate protection against emerging cyber threats.
28 AI-based fraud detection systems improve online banking security.
29 I use a unique password for my online banking account.
30 I enable Multi-Factor Authentication whenever it is available.
31 I regularly update my banking application.
32 I verify website authenticity before entering my banking credentials.
33 I understand how biometric authentication (e.g., Face ID or fingerprint recognition) works when I log in to my online banking account.
34 I understand how my biometric data (e.g., Face ID or fingerprint) is stored and protected when I use biometric authentication for online banking.
35 I am concerned about the privacy risks associated with using biometric authentication for online banking.
36 I trust that my biometric data is securely protected when I use biometric authentication for online banking.
37 Banks should provide clearer information about how biometric data is used and protected when customers use biometric authentication for online banking.
38 Concerns about biometric privacy would affect my willingness to use biometric authentication for online banking.
39 Which biometric authentication method do you currently use for online banking?
40 In your opinion, what is the biggest concern when using biometric authentication for online banking?

In [10]:
all_data = all_data.rename(columns={

    # Demographics
    "Timestamp": "Timestamp",
    "Please confirm the following before proceeding with the survey:\nPlease tick all of the above boxes to continue to the questionnaire.": "Consent",
    "What is your age?": "Age",
    "Gender": "Gender",
    "Highest Level of Education": "Education",
    "How often do you use online banking?": "Banking_Use",
    "Which online banking platform do you use most frequently?": "Platform",

    # Awareness
    "I can recognise phishing emails pretending to be from a bank": "Aware_Phishing",
    "I know that legitimate banks never ask customers to share OTPs or passwords.": "Aware_OTP",
    "I understand how Multi-Factor Authentication (MFA) protects online banking accounts": "Aware_MFA",
    "I know how to verify that a banking website is genuine before entering my login credentials.": "Aware_Website",
    "I understand the risks of using public Wi-Fi for online banking.": "Aware_PublicWiFi",
    "I am aware of AI-generated scams and deepfake fraud targeting banking customers.": "Aware_AI",
    "I know what actions to take if I suspect my online banking account has been compromised.": "Aware_Response",

    # Experience
    "Have you ever received a phishing email pretending to be from a bank?": "Exp_Phishing_Email",
    "Have you ever received a suspicious SMS claiming to be from a bank?": "Exp_Phishing_SMS",
    "Have you ever received a phone call claiming to be from your bank asking for personal information?": "Exp_Phishing_Call",
    "Have you ever clicked on a suspicious banking link?": "Clicked_Suspicious_Link",
    "Have you ever experienced online banking fraud?": "Experienced_Fraud",
    "If yes, how did you identify or respond to the phishing attempt?\n(Select all that apply)": "Fraud_Response",

    # Scenario Questions
    "You receive an email claiming your bank account will be suspended unless you click a link immediately.\nWhat would you do?": "Scenario_Email",
    "Someone claiming to be from your bank asks for your OTP to verify your identity.\nWhat would you do?": "Scenario_OTP",
    "You receive a security alert saying someone logged into your account from another device.\nWhat is your first action?": "Scenario_Login_Alert",
    "You receive a voice call that sounds exactly like your bank manager asking you to urgently approve a transaction.\nWhat would you do?": "Scenario_Deepfake_Call",

    # Opinions
    "Multi-Factor Authentication (MFA) improves online banking security.": "Opinion_MFA",
    "Biometric authentication (Face ID/Fingerprint) provides better protection than passwords alone.": "Opinion_Biometrics",
    "Bank security alerts help prevent cyberattacks.": "Opinion_Alerts",
    "Current front-end security measures provide adequate protection against emerging cyber threats.": "Opinion_FrontEnd",
    "AI-based fraud detection systems improve online banking security.": "Opinion_AI",

    # Behaviour
    "I use a unique password for my online banking account.": "Behaviour_UniquePassword",
    "I enable Multi-Factor Authentication whenever it is available.": "Behaviour_UseMFA",
    "I regularly update my banking application.": "Behaviour_UpdateApp",
    "I verify website authenticity before entering my banking credentials.": "Behaviour_VerifyWebsite",

    # Biometrics
    "I understand how biometric authentication (e.g., Face ID or fingerprint recognition) works when I log in to my online banking account.": "Bio_Understand",
    "I understand how my biometric data (e.g., Face ID or fingerprint) is stored and protected when I use biometric authentication for online banking.": "Bio_DataProtection",
    "I am concerned about the privacy risks associated with using biometric authentication for online banking.": "Bio_PrivacyConcern",
    "I trust that my biometric data is securely protected when I use biometric authentication for online banking.": "Bio_Trust",
    "Banks should provide clearer information about how biometric data is used and protected when customers use biometric authentication for online banking.": "Bio_ClearInfo",
    "Concerns about biometric privacy would affect my willingness to use biometric authentication for online banking.": "Bio_Willingness",

    # Final Questions
    "Which biometric authentication method do you currently use for online banking?": "Biometric_Method",
    "In your opinion, what is the biggest concern when using biometric authentication for online banking?": "Biggest_Concern"

})

In [11]:
#Check the columns name changed
all_data.columns

Index(['Timestamp', 'Consent', 'Age', 'Gender', 'Education', 'Banking_Use',
       'Platform', 'Aware_Phishing', 'Aware_OTP', 'Aware_MFA', 'Aware_Website',
       'Aware_PublicWiFi', 'Aware_AI', 'Aware_Response', 'Exp_Phishing_Email',
       'Exp_Phishing_SMS', 'Exp_Phishing_Call', 'Clicked_Suspicious_Link',
       'Experienced_Fraud', 'Fraud_Response', 'Scenario_Email', 'Scenario_OTP',
       'Scenario_Login_Alert', 'Scenario_Deepfake_Call', 'Opinion_MFA',
       'Opinion_Biometrics', 'Opinion_Alerts', 'Opinion_FrontEnd',
       'Opinion_AI', 'Behaviour_UniquePassword', 'Behaviour_UseMFA',
       'Behaviour_UpdateApp', 'Behaviour_VerifyWebsite', 'Bio_Understand',
       'Bio_DataProtection', 'Bio_PrivacyConcern', 'Bio_Trust',
       'Bio_ClearInfo', 'Bio_Willingness', 'Biometric_Method',
       'Biggest_Concern'],
      dtype='object')

In [12]:
# Check missing values in each column
all_data.isnull().sum()

Timestamp                    0
Consent                      0
Age                          0
Gender                       0
Education                    0
Banking_Use                  0
Platform                     0
Aware_Phishing               0
Aware_OTP                    0
Aware_MFA                    0
Aware_Website                0
Aware_PublicWiFi             0
Aware_AI                     0
Aware_Response               0
Exp_Phishing_Email           0
Exp_Phishing_SMS             0
Exp_Phishing_Call            0
Clicked_Suspicious_Link      0
Experienced_Fraud            0
Fraud_Response              19
Scenario_Email               0
Scenario_OTP                 0
Scenario_Login_Alert         0
Scenario_Deepfake_Call       0
Opinion_MFA                  0
Opinion_Biometrics           0
Opinion_Alerts               0
Opinion_FrontEnd             0
Opinion_AI                   0
Behaviour_UniquePassword     0
Behaviour_UseMFA             0
Behaviour_UpdateApp          0
Behaviour_VerifyWebsite      0
Bio_Understand               0
Bio_DataProtection           0
Bio_PrivacyConcern           0
Bio_Trust                    0
Bio_ClearInfo                0
Bio_Willingness              0
Biometric_Method             0
Biggest_Concern              0
dtype: int64

In [13]:
# Show only columns with missing values
missing_values = all_data.isnull().sum()

missing_values[missing_values > 0]

Fraud_Response    19
dtype: int64

In [14]:
# Fill only the conditional question with "Not Applicable"
all_data["Fraud_Response"] = all_data["Fraud_Response"].fillna("Not Applicable")

In [15]:
#If there is any emojis, then it will be convert to N/A
import re

emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # Emoticons
    "\U0001F300-\U0001F5FF"  # Symbols & Pictographs
    "\U0001F680-\U0001F6FF"  # Transport & Map
    "\U0001F1E0-\U0001F1FF"  # Flags
    "\U00002700-\U000027BF"  # Dingbats
    "\U000024C2-\U0001F251"
    "]+",
    flags=re.UNICODE
)

all_data = all_data.apply(
    lambda col: col.map(
        lambda x: emoji_pattern.sub("N/A", x) if isinstance(x, str) else x
    )
)

In [16]:
# Check the number of duplicate rows
all_data.duplicated().sum()

## Remove duplicate rows if duplicate dispalyed
#all_data = all_data.drop_duplicates()
# Check again
#all_data.duplicated().sum()

np.int64(0)

In [17]:
# Display the data type of each column
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Timestamp                 59 non-null     object
 1   Consent                   59 non-null     object
 2   Age                       59 non-null     object
 3   Gender                    59 non-null     object
 4   Education                 59 non-null     object
 5   Banking_Use               59 non-null     object
 6   Platform                  59 non-null     object
 7   Aware_Phishing            59 non-null     int64
 8   Aware_OTP                 59 non-null     int64
 9   Aware_MFA                 59 non-null     int64
 10  Aware_Website             59 non-null     int64
 11  Aware_PublicWiFi          59 non-null     int64
 12  Aware_AI                  59 non-null     int64
 13  Aware_Response            59 non-null     int64
 14  Exp_Phishing_Email        59 non-null     object
 15  Exp_Phishing_SMS          59 non-null     object
 16  Exp_Phishing_Call         59 non-null     object
 17  Clicked_Suspicious_Link   59 non-null     object
 18  Experienced_Fraud         59 non-null     object
 19  Fraud_Response            59 non-null     object
 20  Scenario_Email            59 non-null     object
 21  Scenario_OTP              59 non-null     object
 22  Scenario_Login_Alert      59 non-null     object
 23  Scenario_Deepfake_Call    59 non-null     object
 24  Opinion_MFA               59 non-null     int64
 25  Opinion_Biometrics        59 non-null     int64
 26  Opinion_Alerts            59 non-null     int64
 27  Opinion_FrontEnd          59 non-null     int64
 28  Opinion_AI                59 non-null     int64
 29  Behaviour_UniquePassword  59 non-null     object
 30  Behaviour_UseMFA          59 non-null     object
 31  Behaviour_UpdateApp       59 non-null     object
 32  Behaviour_VerifyWebsite   59 non-null     object
 33  Bio_Understand            59 non-null     int64
 34  Bio_DataProtection        59 non-null     int64
 35  Bio_PrivacyConcern        59 non-null     int64
 36  Bio_Trust                 59 non-null     int64
 37  Bio_ClearInfo             59 non-null     int64
 38  Bio_Willingness           59 non-null     int64
 39  Biometric_Method          59 non-null     object
 40  Biggest_Concern           59 non-null     object
dtypes: int64(18), object(23)
memory usage: 19.0+ KB

In [18]:
all_data["Timestamp"] = pd.to_datetime(
    all_data["Timestamp"],
    errors="coerce"
)